X("paging",     paging_init,     1)
X("timer",      timer_init,      1)
X("sched",      sched_init,      1)
X("syscalls",   syscall_init,    1)
X("PCI",        pci_init,        1)
X("disk_commands", disk_commands_init, 0)
X("fs_commands",   fs_commands_init,   0)
X("shell_init",    shell_init,        0)
X("commands_init", commands_init,     0)
X("kinit",         kinit_run_all,     0)
X("net",           net_init,          0)
X("UFS mount",     ufs_mount,         0, 2048, 0)
X("shell thread",  sched_create_kthread, 0, "shell", (void(*)(void*))shell_run, NULL)
X("sched_start",   sched_start,       1)
