X("paging",     paging_init,     1)
X("timer",      timer_init,      1)
X("sched",      sched_init,      1)
X("syscalls",   syscall_init,    1)
X("PCI",        pci_init,        1)
X("disk",       disk_init,       1)
X("keyboard",   keyboard_init,   1)
X("net",        net_init,        0)
X("udisk",      udisk_init,      1)
X("kinit",      kinit_run_all,   0)
X("userspace init", spawn_userspace_init, 0)
X("sched_start",  sched_start,   1)
